services:
  - type: web
    name: ocr-flask-app
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-kor
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: your-secret
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
